In [2]:
import numpy as np

#创建numpy.ndarray数组 

In [139]:
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[1,2],[3,4]],dtype = complex)

数组的一般设置有：

In [10]:
print type(a)
print a.dtype
print a.shape
print np.shape(a)
print a.size
print np.size(a)

<type 'numpy.ndarray'>
int64
(2, 2)
(2, 2)
4
4


数组一般处理函数有：

In [106]:
x = np.arange(0,6,2)
print x
print np.sum(x)
print np.prod(x)
print np.cumsum(x)
print np.cumprod(x)
print np.std(x)
print np.var(x)
print np.max(x)
print np.min(x)

[0 2 4]
6
0
[0 2 6]
[0 0 0]
1.63299316186
2.66666666667
4
0


数组的迭代

In [144]:
#迭代内容无索引
x = np.array([[1,2],[3,4],[5,6]])
for row in x:
    print "row:",row
    for row_element in row:
        print "row_element:",row_element
#迭代内容和索引
x = np.array([[1,2],[3,4],[5,6]])
for row_idx,row in enumerate(x):
    print "row_idx:",row_idx ,"row:",row
    for col_idx, row_element in enumerate(row):
        print "col_idx:",col_idx, "row_element:",row_element

row: [1 2]
row_element: 1
row_element: 2
row: [3 4]
row_element: 3
row_element: 4
row: [5 6]
row_element: 5
row_element: 6
row_idx: 0 row: [1 2]
col_idx: 0 row_element: 1
col_idx: 1 row_element: 2
row_idx: 1 row: [3 4]
col_idx: 0 row_element: 3
col_idx: 1 row_element: 4
row_idx: 2 row: [5 6]
col_idx: 0 row_element: 5
col_idx: 1 row_element: 6


数组的堆叠与重复

In [130]:
a = np.array([[1,2],[3,4]])
print a
print np.repeat(a,3) #单纯地元素重复
print np.tile(a,(3,2)) #矩阵拼接
b = np.array([[5,6]])
print np.concatenate((a,b),axis=0)
print np.vstack((a,b))
print np.concatenate((a,b.T),axis=1)
print np.hstack((a,b.T))

[[1 2]
 [3 4]]
[1 1 1 2 2 2 3 3 3 4 4 4]
[[1 2 1 2]
 [3 4 3 4]
 [1 2 1 2]
 [3 4 3 4]
 [1 2 1 2]
 [3 4 3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]
[[1 2 5]
 [3 4 6]]


对于高维数据，可以根据轴进行计算

In [109]:
x = np.arange(0,6)
x = x.reshape(3,2)
print x
print x.max() #全局最大
print x.max(axis=0) #每列最大
print x.max(axis=1) #每行最大

[[0 1]
 [2 3]
 [4 5]]
5
[4 5]
[1 3 5]


关于浅复制与深复制

In [131]:
print "PART1:直接引用"
x = np.arange(0,6)
x = x.reshape(3,2)
x2 = x
x2[0,0] = 10
print x2
print x
print "PART2:reshape引用"
x = np.arange(0,6)
x = x.reshape(3,2)
x2 = x.reshape(1,6)
x2[0,0] = 10
print x2
print x
print "PART3:flatten创建数据副本"
x = np.arange(0,6)
x = x.reshape(3,2)
x2 = x.flatten()
x2[0] = 10
print x2
print x
print "PART4:为了实现高性能计算，Python一般不会复制潜在对象，使用pass by reference"
x = np.arange(0,6)
x = x.reshape(3,2)
x2 = np.copy(x)
x2[0,0] = 10
print x2
print x

PART1:直接引用
[[10  1]
 [ 2  3]
 [ 4  5]]
[[10  1]
 [ 2  3]
 [ 4  5]]
PART2:reshape引用
[[10  1  2  3  4  5]]
[[10  1]
 [ 2  3]
 [ 4  5]]
PART3:flatten创建数据副本
[10  1  2  3  4  5]
[[0 1]
 [2 3]
 [4 5]]
PART4:为了实现高性能计算，Python一般不会复制潜在对象，使用pass by reference
[[10  1]
 [ 2  3]
 [ 4  5]]
[[0 1]
 [2 3]
 [4 5]]


数组赋值如下：

In [18]:
print a
a[0,0] = 0
print a
print b

[[1 2]
 [3 4]]
[[0 2]
 [3 4]]
[[ 1.+0.j  2.+0.j]
 [ 3.+0.j  4.+0.j]]


数组的条件使用如下：

In [157]:
x = np.arange(0,12).reshape(3,4)
print x
if (x>5).any():
    print("at least one element in x is larger than 5")
else:
    print("no element in x is larger than 5")
if (x > 5).all():
    print("all elements in x are larger than 5")
else:
    print("all elements in x are not larger than 5")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
at least one element in x is larger than 5
all elements in x are not larger than 5


数据的类型转换如下：

In [160]:
x = np.array([[-1,0],[-3,3],[4,5]])
print x
print x.dtype
x = x.astype(float)
print x
print x.dtype
x = x.astype(bool)
print x
print x.dtype


[[-1  0]
 [-3  3]
 [ 4  5]]
int64
[[-1.  0.]
 [-3.  3.]
 [ 4.  5.]]
float64
[[ True False]
 [ True  True]
 [ True  True]]
bool


无法将错误的类型复制给ndarray数组：

In [11]:
a[0,0]="hello"

ValueError: invalid literal for long() with base 10: 'hello'

# 数组生成


序列数据

In [21]:
x = np.arange(20,10,-1)
x

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

In [22]:
x = np.linspace(0,10,5)
x

array([  0. ,   2.5,   5. ,   7.5,  10. ])

 网格数据

In [25]:
x,y = np.mgrid[0:6,0:5]
print x
print y

[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


 随机数据

In [26]:
from numpy import random

In [27]:
#均匀随机数[0,1]
random.rand(5,5)

array([[ 0.09919692,  0.44995643,  0.90578017,  0.18181025,  0.16544611],
       [ 0.52577939,  0.2661619 ,  0.14544526,  0.17467566,  0.07716751],
       [ 0.99270601,  0.63966898,  0.39609171,  0.34022083,  0.94142665],
       [ 0.39477782,  0.74222628,  0.1660867 ,  0.22881632,  0.60700693],
       [ 0.7688381 ,  0.07973296,  0.24212191,  0.80267429,  0.12550807]])

In [28]:
#标准正态分布随机数
random.randn(3,3)

array([[-0.06519298, -1.0148678 ,  0.7624279 ],
       [ 0.83847235,  0.10532663, -0.96809228],
       [-1.41104965,  0.60462467,  0.05342115]])

In [30]:
#对角矩阵
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [31]:
#对角线和来自主对角线的偏移
np.diag([1,2,3],k=1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [35]:
#零矩阵
np.zeros([3,2])

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [37]:
#单位矩阵
np.ones([3,2])

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

# 数组属性

自带方法属性

In [52]:
print a 
print a.dtype
print a.itemsize #每个元素字节
print a.nbytes #字节数
print a.shape
print a.ndim #维度


[[1 2]
 [3 4]
 [5 6]]
int64
8
48
(3, 2)
2


索引

In [55]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [57]:
print a[1]
print a[1,:]

[3 4]
[3 4]


In [58]:
print a
a[1,:]=0
print a 

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [0 0]
 [5 6]]


切片操作：

In [89]:
x = random.rand(3,5)
print x
print x[:,[0,2]]

[[ 0.93448632  0.78670721  0.53082731  0.6879397   0.39792245]
 [ 0.40849334  0.39022913  0.64859412  0.59889672  0.58325598]
 [ 0.0906302   0.66651492  0.06256449  0.92408218  0.97363145]]
[[ 0.93448632  0.53082731]
 [ 0.40849334  0.64859412]
 [ 0.0906302   0.06256449]]


In [62]:
x[:,1:4]

array([[ 0.46740195,  0.0768382 ,  0.07346568],
       [ 0.48948803,  0.29960272,  0.91767398],
       [ 0.5598798 ,  0.91672971,  0.60836121]])

In [64]:
x[:,::-1]

array([[ 0.179725  ,  0.07346568,  0.0768382 ,  0.46740195,  0.32740686],
       [ 0.5135012 ,  0.91767398,  0.29960272,  0.48948803,  0.95433032],
       [ 0.57635566,  0.60836121,  0.91672971,  0.5598798 ,  0.4558267 ]])

In [65]:
print x[:,:2] #前两列元素
print x[:,2:] #前两列后的元素
print x[:,-1] #最后一列后的元素
print x[:,-3:] #最后三列元素

[[ 0.32740686  0.46740195]
 [ 0.95433032  0.48948803]
 [ 0.4558267   0.5598798 ]]
[[ 0.0768382   0.07346568  0.179725  ]
 [ 0.29960272  0.91767398  0.5135012 ]
 [ 0.91672971  0.60836121  0.57635566]]
[ 0.179725    0.5135012   0.57635566]
[[ 0.0768382   0.07346568  0.179725  ]
 [ 0.29960272  0.91767398  0.5135012 ]
 [ 0.91672971  0.60836121  0.57635566]]


In [69]:
# 多维数组切片
x = np.array([[n+5+m*10 for n in range(5)] for m in range(5)])
print x
print x[0:3,0:3]
print x[::2,::2]
print x[[1,1,3],[1,2,0]] #取其中元素

[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [25 26 27 28 29]
 [35 36 37 38 39]
 [45 46 47 48 49]]
[[ 5  6  7]
 [15 16 17]
 [25 26 27]]
[[ 5  7  9]
 [25 27 29]
 [45 47 49]]
[16 17 35]


In [70]:
# 索引掩码
x = np.arange(0,10,0.5)
print x
mask = (5<x)*(x<7.5)
print mask
x[mask]

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.
  7.5  8.   8.5  9.   9.5]
[False False False False False False False False False False False  True
  True  True  True False False False False False]


array([ 5.5,  6. ,  6.5,  7. ])

从数组中提取元素并创建数组

In [74]:
x = np.arange(0,10,0.5)
print x
mask = (5<x)*(x<7.5)
print mask
indices = np.where(mask)
print indices
print x[mask]
print x[indices]

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.
  7.5  8.   8.5  9.   9.5]
[False False False False False False False False False False False  True
  True  True  True False False False False False]
(array([11, 12, 13, 14]),)
[ 5.5  6.   6.5  7. ]
[ 5.5  6.   6.5  7. ]


In [77]:
# 利用diag提取主对角线元素
x = random.randn(5,5)
print x
print np.diag(x)

[[ 0.35053038 -2.56973724 -0.05651981 -1.32248042  2.35476321]
 [ 0.2212736  -0.22289291 -0.40078711  0.94204767  0.64532453]
 [ 0.63454306  1.23743713  0.34034757  0.81521901  1.57708365]
 [-0.51013868  0.98183459  1.12518085 -0.12639426 -0.21625004]
 [ 0.39742529 -0.09494752  0.79372219  0.25211267  0.10551674]]
[ 0.35053038 -0.22289291  0.34034757 -0.12639426  0.10551674]


In [87]:
# 利用take从数组中提取元素
x = np.arange(0,6)
print x
print x[[0,3,4]]
print x.take([0,3,4])
print np.take(range(0,6),[0,3,4])

[0 1 2 3 4 5]
[0 3 4]
[0 3 4]
[0 3 4]


# 矢量化操作

In [91]:
# np.array数组默认的操作是针对单个元素的操作
x = np.arange(0,5)
print x
print x*2
print x+2
print x**2
print x*x


[0 1 2 3 4]
[0 2 4 6 8]
[2 3 4 5 6]
[ 0  1  4  9 16]
[ 0  1  4  9 16]


In [93]:
# 智能行乘操作
A = np.array([[ 0,  2,  4,  6,  8],
                   [2,  4,  6,  8,  10]])
v1 = np.arange(0, 5)
print A
print v1
print A.shape,v1.shape
print A*v1

[[ 0  2  4  6  8]
 [ 2  4  6  8 10]]
[0 1 2 3 4]
(2, 5) (5,)
[[ 0  2  8 18 32]
 [ 0  4 12 24 40]]


In [99]:
# 矩阵乘法
A = np.array([[ 0,  2,  4,  6,  8],
                   [2,  4,  6,  8,  10]])
v1 = np.arange(0, 5)
print A
print v1
print A.shape,v1.shape
#方法一
print "method 1:"
print np.dot(A,v1) #矩阵乘法
print np.dot(A,v1).shape #矩阵乘法
print np.dot(v1,v1) #内积向量乘法
#方法二
print "method 2:"
A = np.matrix(A)
v1 = np.matrix(v1).T #转置
print A
print v1
print A *v1

[[ 0  2  4  6  8]
 [ 2  4  6  8 10]]
[0 1 2 3 4]
(2, 5) (5,)
method 1:
[60 80]
(2,)
30
method 2:
[[ 0  2  4  6  8]
 [ 2  4  6  8 10]]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[60]
 [80]]


In [103]:
#矩阵操作
x = np.matrix([[1j, 2j], [3j, 4j]])
print x
print x.T
print np.conjugate(x) #共轭
print x.H #转置共轭
print np.real(x)
print np.imag(x)
print np.angle(x)
print np.abs(x)

[[ 0.+1.j  0.+2.j]
 [ 0.+3.j  0.+4.j]]
[[ 0.+1.j  0.+3.j]
 [ 0.+2.j  0.+4.j]]
[[ 0.-1.j  0.-2.j]
 [ 0.-3.j  0.-4.j]]
[[ 0.-1.j  0.-3.j]
 [ 0.-2.j  0.-4.j]]
[[ 0.  0.]
 [ 0.  0.]]
[[ 1.  2.]
 [ 3.  4.]]
[[ 1.57079633  1.57079633]
 [ 1.57079633  1.57079633]]
[[ 1.  2.]
 [ 3.  4.]]


In [104]:
#矩阵计算
x = np.matrix([[1+1j, 2j], [4+3j, 4j]])
print x
# 计算矩阵的逆
print x.I
print np.linalg.inv(x)
print x * x.I
#计算矩阵的行列式
print np.linalg.det(x)

[[ 1.+1.j  0.+2.j]
 [ 4.+3.j  0.+4.j]]
[[-0.8+0.4j  0.4-0.2j]
 [ 0.2-1.1j -0.1+0.3j]]
[[-0.8+0.4j  0.4-0.2j]
 [ 0.2-1.1j -0.1+0.3j]]
[[  1.00000000e+00 +5.55111512e-17j  -1.11022302e-16 -2.77555756e-17j]
 [  0.00000000e+00 +1.11022302e-16j   1.00000000e+00 -5.55111512e-17j]]
(2-4j)


In [149]:
#非矢量化函数
def Theta(x):
    """
    Scalar implemenation of the Heaviside step function
    """
    if x>=0:
        return 1
    else:
        return 0
Theta_vec = np.vectorize(Theta) #转化为矢量计算
x = np.arange(-5,5)
Theta_vec(x)

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [150]:
#矢量化函数
def Theta(x):
    """
    Vector-aware implemenation of the Heaviside step function.
    """
    return (x>=0)*1
x = np.arange(-5,5)
Theta(x)

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

# 文件IO

## 转化为csv或tsv

In [41]:
x = random.rand(3,2)
x

array([[ 0.89063165,  0.21119563],
       [ 0.61440284,  0.97998172],
       [ 0.68933552,  0.63213934]])

In [42]:
np.savetxt("random-matrix.csv",x)

In [43]:
!cat random-matrix.csv

8.906316498274183813e-01 2.111956330532629433e-01
6.144028387950468684e-01 9.799817180444337916e-01
6.893355178118952820e-01 6.321393425877656069e-01


## np的原生格式

In [45]:
np.save("random-matrix.npy", x)
!file random-matrix.npy

random-matrix.npy: data


In [47]:
np.load("random-matrix.npy")

array([[ 0.89063165,  0.21119563],
       [ 0.61440284,  0.97998172],
       [ 0.68933552,  0.63213934]])